publicHoistPattern:
  - "workbox-window"
onlyBuiltDependencies:
overrides:
  "@ionic/core": "npm:voyager-ionic-core@8.7.6"
patchedDependencies:
  "@capacitor/keyboard": "patches/@capacitor__keyboard.patch"
  "@capacitor/android": "patches/@capacitor__android.patch"
  "@capacitor/haptics": "patches/@capacitor__haptics.patch"
  "openapi-fetch": "patches/openapi-fetch.patch"
updateConfig:
  ignoreDependencies:
    - "history"
    - "@types/history"
    - "react-router"
    - "react-router-dom"
    - "@types/react-router"
    - "@types/react-router-dom"
