overrides:
  "@ionic/core": npm:voyager-ionic-core@8.8.12

patchedDependencies:
  "@capacitor/haptics": patches/@capacitor__haptics.patch
  "@capacitor/keyboard@8.0.5": patches/@capacitor__keyboard@8.0.5.patch
  editate@0.6.9: patches/editate@0.6.9.patch
  openapi-fetch: patches/openapi-fetch.patch

publicHoistPattern:
  - workbox-window

updateConfig:
  ignoreDependencies:
    - history
    - "@types/history"
    - react-router
    - react-router-dom
    - "@types/react-router"
    - "@types/react-router-dom"

minimumReleaseAge: 0

allowBuilds:
  core-js: true
  esbuild: true
