# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    cocoapods(clean_install: true)
    match(type: "appstore")
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      output_name: "Voyager-iOS-#{ENV['GITHUB_REF_NAME']}-Build.ipa"
    )
    # upload_to_testflight(
    #   ipa: "Voyager-iOS-#{ENV['GITHUB_REF_NAME']}-Build.ipa"
    #   app_identifier: "app.vger.voyager",
    #   api_key_path: "authkey.json",
    #   skip_waiting_for_build_processing: true,
    #   changelog: "Upload from GitHub Actions, ref #{ENV['GITHUB_REF']}, sha #{ENV['GITHUB_SHA']}, msg #{ENV['COMMIT_MSG']}"
    # )
  end
end

# platform :android do
#   lane :playstore do
#     gradle(
#       task: 'assemble',
#       build_type: 'Release'
#     )
#     upload_to_play_store(
#       release_status: 'draft'
#     )
#   end
# end