import {
  bicycleOutline,
  chatbubblesOutline,
  filmOutline,
  gameControllerOutline,
  hammerOutline,
  happyOutline,
  laptopOutline,
  newspaperOutline,
  schoolOutline,
} from "ionicons/icons";

export default [
  {
    title: "Tech & Open Source",
    description:
      "technology, linux, privacy, selfhosted, fediverse, sysadmin and more",
    icon: laptopOutline,
    communities: [
      "https://lemmy.world/c/technology",
      "https://lemmy.ml/c/linux",
      "https://lemmy.world/c/linux",
      "https://lemmy.ml/c/privacy",
      "https://lemmy.ca/c/privacy",
      "https://lemmy.ml/c/opensource",
      "https://lemmy.world/c/selfhosted",
      "https://lemmy.ml/c/selfhost",
      "https://lemmy.ml/c/fediverse",
      "https://lemmy.world/c/fediverse",
      "https://programming.dev/c/programming",
      "https://lemmy.ml/c/programmerhumor",
      "https://programming.dev/c/programmer_humor",
      "https://lemmy.world/c/sysadmin",
      "https://lemmy.world/c/hardware",
      "https://programming.dev/c/raspberry_pi",
    ],
  },
  {
    title: "Gaming",
    description: "games, retro, nintendo, pcmasterrace, linux_gaming and more",
    icon: gameControllerOutline,
    communities: [
      "https://lemmy.ml/c/gaming",
      "https://lemmy.world/c/games",
      "https://sh.itjust.works/c/games",
      "https://lemmy.world/c/retrogaming",
      "https://lemmy.world/c/nintendo",
      "https://lemmy.world/c/pcmasterrace",
      "https://lemmy.ml/c/steam",
      "https://sopuli.xyz/c/steamdeck",
      "https://lemmy.ml/c/linux_gaming",
      "https://lemmy.world/c/linux_gaming",
      "https://sh.itjust.works/c/patientgamers",
      "https://lemmy.ml/c/patientgamers",
    ],
  },
  {
    title: "Memes & Humor",
    description: "memes, funny, dadjokes, xkcd, lemmyshitpost and more",
    icon: happyOutline,
    communities: [
      "https://lemmy.ml/c/memes",
      "https://sopuli.xyz/c/memes",
      "https://lemmy.ml/c/programmerhumor",
      "https://programming.dev/c/programmer_humor",
      "https://lemmy.world/c/comicstrips",
      "https://lemmy.world/c/lemmyshitpost",
      "https://sh.itjust.works/c/funny",
      "https://lemmy.world/c/dadjokes",
      "https://lemmy.world/c/xkcd",
      "https://midwest.social/c/lotrmemes",
      "https://lemmy.world/c/starwarsmemes",
      "https://ttrpg.network/c/rpgmemes",
    ],
  },
  {
    title: "News & Politics",
    description: "world, worldnews, news, politics, workreform and more",
    icon: newspaperOutline,
    communities: [
      "https://lemmy.world/c/world",
      "https://lemmy.ml/c/worldnews",
      "https://lemmy.world/c/news",
      "https://lemmy.world/c/politics",
      "https://lemmy.world/c/workreform",
      "https://lemmy.world/c/aboringdystopia",
    ],
  },
  {
    title: "Casual & Social",
    description:
      "aww, pics, asklemmy, nostupidquestions, mildlyinfuriating and more",
    icon: chatbubblesOutline,
    communities: [
      "https://lemmy.ml/c/asklemmy",
      "https://lemmy.world/c/asklemmy",
      "https://lemmy.world/c/nostupidquestions",
      "https://lemmy.world/c/mildlyinfuriating",
      "https://lemmy.world/c/mildlyinteresting",
      "https://lemmy.world/c/aww",
      "https://lemmy.ml/c/aww",
      "https://lemmy.world/c/pics",
      "https://lemmy.world/c/cat",
    ],
  },
  {
    title: "Science & Learning",
    description:
      "science, askscience, explainlikeimfive, youshouldknow and more",
    icon: schoolOutline,
    communities: [
      "https://lemmy.ml/c/science",
      "https://lemmy.world/c/science",
      "https://lemmy.world/c/askscience",
      "https://lemmy.world/c/explainlikeimfive",
      "https://lemmy.world/c/youshouldknow",
      "https://lemmy.ml/c/todayilearned",
      "https://lemmy.world/c/til",
      "https://lemmy.world/c/showerthoughts",
    ],
  },
  {
    title: "Movies, TV, & Pop Culture",
    description: "movies, tv, trailers, sciencefiction",
    icon: filmOutline,
    communities: [
      "https://lemmy.world/c/movies",
      "https://lemmy.ml/c/movies",
      "https://piefed.social/c/television",
      "https://lemmy.blahaj.zone/c/trailers",
      "https://lemmy.world/c/filmsframes",
      "https://lemmy.world/c/sciencefiction",
      "https://startrek.website/c/startrek",
    ],
  },
  {
    title: "Hobbies & DIY",
    description:
      "3dprinting, homeimprovement, homeassistant, mechanicalkeyboards",
    icon: hammerOutline,
    communities: [
      "https://lemmy.world/c/3dprinting",
      "https://lemmy.world/c/homeimprovement",
      "https://lemmy.world/c/homeassistant",
      "https://lemmy.ml/c/mechanicalkeyboards",
    ],
  },
  {
    title: "Transport",
    description: "Fuck, and I can’t stress this enough, them cars",
    icon: bicycleOutline,
    communities: [
      "https://lemmy.ml/c/fuck_cars",
      "https://lemmy.world/c/fuckcars",
      "https://lemmy.blahaj.zone/c/trams_trolleys_streetcars",
      "https://lemmy.world/c/cargobikes",
      "https://lemmy.ca/c/bicycles",
    ],
  },
];
