# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App

end

target 'VoyagerActionExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoyagerActionExtension

end

target 'VoyagerWatch Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoyagerWatch Watch App

end
