require_relative '../../node_modules/.pnpm/@capacitor+ios@7.0.1_@capacitor+core@7.0.1/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@7.0.1_@capacitor+core@7.0.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@7.0.1_@capacitor+core@7.0.1/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppIcon', :path => '../../node_modules/.pnpm/@capacitor-community+app-icon@6.0.0_@capacitor+core@7.0.1/node_modules/@capacitor-community/app-icon'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@7.0.0_patch_hash=daa342ffd526f01bd99bc1242d366ebc0d25fc5ec30939e5be0_45e4eec990dc2777ab292cc0f0341903/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@7.0.0_patch_hash=a9b910edbb5059e863b0b44c347168d2bf0b0a421868be03f7_7fa9f73596a3c66c6ad827db199ae4cb/node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/.pnpm/@capacitor+network@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/network'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@7.0.0_@capacitor+core@7.0.1/node_modules/@capacitor/status-bar'
  pod 'CapacitorAndroidNavMode', :path => '../../node_modules/.pnpm/capacitor-android-nav-mode@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-android-nav-mode'
  pod 'CapacitorApplicationContext', :path => '../../node_modules/.pnpm/capacitor-application-context@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-application-context'
  pod 'CapacitorBiometricLock', :path => '../../node_modules/.pnpm/capacitor-biometric-lock@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-biometric-lock'
  pod 'CapacitorClearCache', :path => '../../node_modules/.pnpm/capacitor-clear-cache@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-clear-cache'
  pod 'CapacitorLaunchNative', :path => '../../node_modules/.pnpm/capacitor-launch-native@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-launch-native'
  pod 'CapacitorPluginSafeArea', :path => '../../node_modules/.pnpm/capacitor-plugin-safe-area@3.0.4_@capacitor+core@7.0.1/node_modules/capacitor-plugin-safe-area'
  pod 'CapacitorReader', :path => '../../node_modules/.pnpm/capacitor-reader@0.4.0_@capacitor+core@7.0.1/node_modules/capacitor-reader'
  pod 'CapacitorStashMedia', :path => '../../node_modules/.pnpm/capacitor-stash-media@2.2.0_@capacitor+core@7.0.1/node_modules/capacitor-stash-media'
  pod 'CapacitorTips', :path => '../../node_modules/.pnpm/capacitor-tips@1.1.1_@capacitor+core@7.0.1/node_modules/capacitor-tips'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
